version: "3"
services:
  postgres:
    container_name: tagger-db
    image: postgres:12.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  server:
    container_name: tagger-server
    image: elixir:1.9.4-slim
    command: ["tail", "-f", "/dev/null"]
    ports:
      - 4000:4000
    volumes:
      - ./:/opt/app

